package Enum;
 
/**
*Enumeration of possible instruction types for a client-server communication.
*/
public enum Instruction {
	// server
	User_not_found,
	Area_Manager_Details_Found,
	Facilities_In_Area_List,
	Nothing_To_Get,
	Facility_Area_Value,
	Order_Update,
	All_Product_list,
	User_Orders,
	Order_status_updated,
	Shipments_by_area,
	Received_shipments_by_area,
	Shipment_status_updated,
	Shipment_estimate_date_updated,
	Customer_area_for_calculate,
	PickUp_Order_Values,
	Report_Area_Manager_NotFound,
	Report_Area_Manager_Found,
	Shipment_Report_Return,
	Get_Sales_By_Area_Success,
	All_salesPatterns_list,
	Get_Sale_Facility,
	All_Operating_Workers,
	Set_Execution_Instructions_List,
	User_found,
	User_loggedIn_Changed,
	All_NotApprovedUser_list,
	Get_Subscriber_Data,
	User_for_SMS_and_email_found,
	User_for_registeration_found,
	Subscriber_number_max,
	Worker_details,
	User_updaed_in_user_table_and_registeredCustomer_table,
	Worker_permissions_updated,
	
	// client
	Get_user_details,
	Get_Subscriber_EKT_Login,
	Set_User_loggedIn,
	Update_user_details_After_RegisteredCustomer_Registration,
	Get_max_subscriber_number,
	Update_subscriber_details_After_Subscriber_Registration,
	Update_worker_permissions_to_RegisteredCustomer,
	Update_worker_permissions_to_Subscriber,
	Get_worker_extra_details_as_RegisteredCustomer,
	Get_all_Product_list,
	Get_all_Users_NotApproved_list,
	Update_User_userStatus,
	Get_Area_Manager_Details,
	Set_Product_ThresholdLevel,
	Get_Report_Area_Manager,
	Get_Facility_Products,
	Get_Operating_Workers,
	Get_Execution_Instructions_List,
	Update_Execution_Instructions,
	Set_New_Execution_Instructions,
	Update_Inventory_Execution_Instructions,
	Update_Status_Execution_Instructions,
	Update_Product_Inventory,
	Get_facilities_in_Area,
	Order_Get_Products,
	Add_Order_To_Invetory,
	Get_user_details_For_Registeration,
	Make_An_Order,
	Get_Sales_By_Area,
	Update_Sale_Status,
	Get_all_Sales_Pattern_list,
	set_Sales_Pattern,
	add_New_Sale,
	Get_Subscriber_Details,
	Get_Facility_Area,
	Shipment_Report_Search,
	Get_user_orders,
	Update_order,
	Get_shipments_of_area,
	Update_shipment_status,
	Get_recived_shipments_for_confirmation,
	Calculate_delivery_time,
	Update_shipment_estimate_date,
	Get_PickUp_Order,
	SET_PickUp_Date,
	Disconnect_From_Server,
	Get_user_details_for_send_email_and_sms,
	New_Notification, 

	
}

